-- Таблица юзеров
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR NOT NULL,
    login VARCHAR NOT NULL,
    name VARCHAR,
    birthday DATE NOT NULL
);

-- Таблица рейтингов mpa
CREATE TABLE IF NOT EXISTS mpa_rating (
    id INT PRIMARY KEY,
    name VARCHAR NOT NULL
);

-- Таблица фильмов
CREATE TABLE IF NOT EXISTS films (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    description VARCHAR(200),
    release_date DATE NOT NULL,
    duration INT NOT NULL,
    mpa_rating_id INT REFERENCES mpa_rating(id)
);

-- Таблица жанров
CREATE TABLE IF NOT EXISTS genres (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL
);

-- Таблица связей фильмов и их жанров
CREATE TABLE IF NOT EXISTS film_genre (
    film_id BIGINT REFERENCES films(id),
    genre_id BIGINT REFERENCES genres(id),
    PRIMARY KEY (film_id, genre_id)
);

-- Таблица лайков фильмов юзерами
CREATE TABLE IF NOT EXISTS user_like (
    film_id BIGINT REFERENCES films(id),
    user_id BIGINT REFERENCES users(id),
    PRIMARY KEY (film_id, user_id)
);

-- Таблица статусов дружбы
CREATE TABLE IF NOT EXISTS friendship_status (
    id INT PRIMARY KEY,
    name VARCHAR NOT NULL
);

-- Таблица друзей
CREATE TABLE IF NOT EXISTS friends (
    user_id BIGINT REFERENCES users(id),
    friend_id BIGINT REFERENCES users(id),
    PRIMARY KEY (user_id, friend_id)
);

